languages:
  - "your-language"

load_path: "your-path"

# sources:
#   - "your-source"

streaming: False

pre_filter:
  script_regex: true
  lang_id: false

deduplicate:
  exact_match: true
  min_hash: true
  n_shingles: 3
  jaccard_threshold: 0.85

threshold:
  thresholds:
    length_words: 50
    doc_mean_word_length: 3
    frac_lines_end_ellipsis: 0.3
    frac_symbol_to_words: 0.1
    frac_no_script_words: 0.8

partition:
  metrics:
    - "length_words"
    - "doc_mean_word_length"
    - "frac_lines_end_ellipsis"
    - "frac_symbol_to_words"
    - "frac_no_script_words"
  split_method: "balanced_chars"
  quality: true

split:
  test_size: 0.1
  seed: 42
  shuffle: true

export: false
push_to_hub: false
