load_path: "./config/model/mbert/config.json"

training_parameters:
  model_type: "bert"
  task: "mlm"
  max_length: 128
  mask_prob: 0.4
  num_train_epochs: 1
  batch_size: 64
  lr: 1e-03 #DO NOT CHANGE THIS
  padding_strategy: "longest"
  grad_accumulation_steps: 1
  mixed_precision: "bf16"

test_path: "WikiQuality/multilingual_prefilter"
export: true
push_to_hub: true
checkpoint: true
